export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const DEMO = 'DEMO';
export const DEMO_SUCCESS = 'DEMO_SUCCESS';
export const DEMO_FAILURE = 'DEMO_FAILURE';

export const SECOND_DEMO = 'SECOND_DEMO';
export const SECOND_DEMO_SUCCESS = 'SECOND_DEMO_SUCCESS';
export const SECOND_DEMO_FAILURE = 'SECOND_DEMO_FAILURE';
export const GET_ANIMAL_KINGDOM_CAFE = 'GET_ANIMAL_KINGDOM_CAFE';
export const ADD_ANIMAL_KINGDOM_CAFE = 'ADD_ANIMAL_KINGDOM_CAFE';
export const ADDED_ANIMAL_KINGDOM_CAFE = 'ADDED_ANIMAL_KINGDOM_CAFE';
export const GET_ANIMAL_KINGDOM_CAFE_ITEM = 'GET_ANIMAL_KINGDOM_CAFE_ITEM';
export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART';
export const ADD_TO_SHOPPING_CART_SUCCESSFULL =
  'ADD_TO_SHOPPING_CART_SUCCESSFULL';
export const GET_FROM_SHOPPING_CART = 'GET_FROM_SHOPPING_CART';
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const MISSING_PET = 'MISSING_PET';
export const GET_FROM_ORDERS = 'GET_FROM_ORDERS';
export const GET_COMPLETED_FROM_ORDERS = 'GET_COMPLETED_FROM_ORDERS';
export const GET_MISSING_PET = 'GET_MISSING_PET';
export const GROUP_CHAT_CREATED = 'GROUP_CHAT_CREATED';
export const GET_CHAT_LIST = 'GET_CHAT_LIST';
export const GET_MARKETPLACE_LIST = 'GET_MARKETPLACE_LIST';
export const GET_RATINGS = 'GET_RATINGS';
export const GET_ISRATED_ITEM = 'GET_ISRATED_ITEM';
export const GET_USERSTORIES = 'GET_USERSTORIES';
export const GET_USERSTORIES_COMMENTS = 'GET_USERSTORIES_COMMENTS';
export const GET_ALLGROUPS = 'GET_ALLGROUPS';
export const GET_ALLGROUP_MEMBERS = 'GET_ALLGROUP_MEMBERS';
export const GET_PODCAST = 'GET_PODCAST';
export const GET_PODCAST_COMMENTS = 'GET_PODCAST_COMMENTS';
export const IS_FRIEND_REQUEST_SENT = 'IS_FRIEND_REQUEST_SENT';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const GET_ALL_FRIEND_REQUESTS = 'GET_ALL_FRIEND_REQUESTS';
export const FRIEND_REQUEST_CONFIRMED = 'FRIEND_REQUEST_CONFIRMED';
export const GET_ALL_USER_FRIENDS = 'GET_ALL_USER_FRIENDS';
export const GET_INDIVIDUAL_FRIEND = 'GET_INDIVIDUAL_FRIEND';
export const GET_RECOMMENDATION_FRIENDS = 'GET_RECOMMENDATION_FRIENDS';
export const CANCEL_GET_INDIVIDUAL_FRIEND = 'CANCEL_GET_INDIVIDUAL_FRIEND';

// DISCOVER GROUPS NEW

export const GET_DISCOVER_GROUPS = 'GET_DISCOVER_GROUPS';
export const JOIN_GROUP = 'JOIN_GROUP';
export const GET_GROUP_DETAILS = 'GET_GROUP_DETAILS';
export const GET_INVITED_MEMBERS = 'GET_INVITED_MEMBERS';
export const GET_GROUP_INFORMATION='GET_GROUP_INFORMATION'

// USER NEW

export const GET_USER = 'GET_USER';
